# Generated by Django 5.2.11 on 2026-02-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
