# Generated by Django 5.2.11 on 2026-02-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_devedor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='preco_atacado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='quantidade_atacado',
            field=models.IntegerField(default=100),
        ),
    ]
