# Generated by Django 5.2.11 on 2026-02-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='parceiro',
            field=models.BooleanField(default=False),
        ),
    ]
