# Generated by Django 5.2.11 on 2026-02-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_cliente_parceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
