# Generated by Django 5.2.11 on 2026-02-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_venda_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente_avulso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='pago',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
