# Generated by Django 6.0.4 on 2026-08-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_venda_data_alter_venda_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoVendas',
            fields=[
            ],
            options={
                'verbose_name': 'Resumo de Vendas',
                'verbose_name_plural': 'Resumo de Vendas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.venda',),
        ),
    ]
